### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by jacqueswww**
Figured out how to get a Docker image going, because `gcc` is a requirement the total size clocks in at 263MB. 

Can also be tested using:
```
docker pull jacqueswww/nlvm
docker run -v $(pwd):/code/ nlvm c -r /code/test.nim
```

### CODE REVIEW

**Comment by arnetheduck** [comment]
hm, which docker version are you on?

```
[arnetheduck@tempus nlvm]$ make docker
docker build . -t nlvm --no-cache
Sending build context to Docker daemon 55.29 GB
Step 1/8 : FROM ubuntu:18.04 AS build
Error parsing reference: "ubuntu:18.04 AS build" is not a valid repository/tag: invalid reference format
[arnetheduck@tempus nlvm]$ docker --version
Docker version 1.13.1, build 1185cfd/1.13.1

```

**Comment by jacqueswww** [comment]
> hm, which docker version are you on?
> 
> ```
> [arnetheduck@tempus nlvm]$ make docker
> docker build . -t nlvm --no-cache
> Sending build context to Docker daemon 55.29 GB
> Step 1/8 : FROM ubuntu:18.04 AS build
> Error parsing reference: "ubuntu:18.04 AS build" is not a valid repository/tag: invalid reference format
> [arnetheduck@tempus nlvm]$ docker --version
> Docker version 1.13.1, build 1185cfd/1.13.1
> ```
```
$ docker --version
Docker version 19.03.1-ce, build 74b1e89e8a
```
and 
```
docker --version
Docker version 17.12.0-ce, build c97c6d6
```
Using `AS build` is very beneficial for image size, so I'd suggest we get a docker version that supports it.

**Comment by arnetheduck** [comment]
ok, getting closer but:

```
../Nim/bin/nim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ../Nim/bin/nim)
Command exited with non-zero status 1
0.00user 0.00system 0:00.00elapsed 33%CPU (0avgtext+0avgdata 604maxresident)k
6192inputs+0outputs (1major+49minor)pagefaults 0swaps
make: *** [nlvm/nlvmr] Error 1
```

I noticed that the build environment, including nim and llvm, is being copied into the docker - this is likely where the problem lies: binaries from the docker host should not be used inside the docker so they need to be excluded when copying stuff to docker!

to repro, build nlvm using `make`, then run `make docker` - if lots and lots of GB of data are being transferred into the docker, something is wrong.

**Comment by jacqueswww** [comment]
I was unable to avoid this, because docker needs current directory to build from. Other option is to do a git checkout in the Dockerfile and move the Dockerfile to an empty directory? Just clean your current files before building the Docker image and it should build as Docker make will fetch and repopulate the rest of the files.

**Comment by refi64** [comment]
You can use a [.dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file) to ignore the built files when adding it.

**Review by refi64 — COMMENTED** [review]
This code is kinda confusing:

- Why does the nlvm directory need to have a git commit in its name?
- Why *can't* the files just go in /usr/bin, etc?
- Why is there a *directory* in /bin that contains library data? If the answer to this and the above question are "because nlvm wants it there", you can just install nlvm and needed files to e.g. /usr/lib/nlvm/..., then symlink it to /usr/bin.
- Why is /usr/lib/nim created but empty?
- Wouldn't it just be easier to do a clean and cp over git archive?

IMO at minimum some more comments would be pretty helpful...

(Also ignore the random intrusion, I've been watching this repo for quite a while and also use Docker/podman a lot, so I figured I should make myself useful. ¯\\\_(ツ)\_/¯)

**Comment by jacqueswww** [comment]
Sure no problem, most of those changes were done to just make it work and the directory choices was based off of `make-dist.sh`. Let me make path changes + .dockerignore.

**Comment by jacqueswww** [comment]
@arnetheduck please try now :)

**Comment by arnetheduck** [comment]
closer :)

```
...

sh build.sh
/bin/sh: 1: cd: can't cd to Nim
Cloning into 'csources'...
Checking out files: 100% (10876/10876), done.
Already up to date.

...

m.o c_code/2_2/stdlib_osproc.nim.o c_code/1_2/stdlib_sets.nim.o c_code/2_2/pathutils.nim.o c_code/1_2/ropes.nim.o c_code/1_2/stdlib_tables.nim.o c_code/1_2/lineinfos.nim.o c_code/2_2/platform.nim.o c_code/1_2/prefixmatches.nim.o c_code/2_2/stdlib_strformat.nim.o c_code/2_2/stdlib_terminal.nim.o c_code/2_2/options.nim.o c_code/2_2/msgs.nim.o c_code/1_2/wordrecg.nim.o c_code/1_2/idents.nim.o c_code/1_2/condsyms.nim.o c_code/1_2/stdlib_sha1.nim.o c_code/2_2/stdlib_lexbase.nim.o c_code/1_2/stdlib_parsejson.nim.o c_code/2_2/stdlib_json.nim.o c_code/2_2/extccomp.nim.o c_code/2_2/nimblecmd.nim.o c_code/2_2/stdlib_parseopt.nim.o c_code/2_2/commands.nim.o c_code/1_2/llstream.nim.o c_code/1_2/nimlexbase.nim.o c_code/2_2/lexer.nim.o c_code/2_2/nimconf.nim.o c_code/1_2/stdlib_intsets.nim.o c_code/1_2/idgen.nim.o c_code/1_2/ast.nim.o c_code/1_2/rodutils.nim.o c_code/2_2/astalgo.nim.o c_code/1_2/parser.nim.o c_code/1_2/renderer.nim.o c_code/1_2/filters.nim.o c_code/1_2/filter__tmpl.nim.o c_code/1_2/syntaxes.nim.o c_code/1_2/trees.nim.o c_code/2_2/types.nim.o c_code/1_2/treetab.nim.o c_code/1_2/incremental.nim.o c_code/1_2/btrees.nim.o c_code/1_2/stdlib_md5.nim.o c_code/1_2/modulegraphs.nim.o c_code/1_2/magicsys.nim.o c_code/1_2/bitsets.nim.o c_code/1_2/nimsets.nim.o c_code/2_2/semfold.nim.o c_code/2_2/modulepaths.nim.o c_code/1_2/reorder.nim.o c_code/1_2/passes.nim.o c_code/1_2/vmdef.nim.o c_code/1_2/semdata.nim.o c_code/1_2/linter.nim.o c_code/1_2/nimfix7prettybase.nim.o c_code/1_2/lookups.nim.o c_code/1_2/semtypinst.nim.o c_code/1_2/parampatterns.nim.o c_code/1_2/lowerings.nim.o c_code/1_2/_7lib7packages7docutils7rstast.nim.o c_code/1_2/_7lib7packages7docutils7rst.nim.o c_code/1_2/_7lib7packages7docutils7highlite.nim.o c_code/2_2/_7lib7packages7docutils7rstgen.nim.o c_code/1_2/stdlib_xmltree.nim.o c_code/1_2/stdlib_uri.nim.o c_code/1_2/stdlib_cgi.nim.o c_code/1_2/typesrenderer.nim.o c_code/2_2/docgen.nim.o c_code/2_2/sigmatch.nim.o c_code/1_2/importer.nim.o c_code/1_2/procfind.nim.o c_code/2_2/pragmas.nim.o c_code/1_2/saturate.nim.o c_code/1_2/guards.nim.o c_code/1_2/sighashes.nim.o c_code/1_2/sempass2.nim.o c_code/1_2/cgmeth.nim.o c_code/1_2/aliases.nim.o c_code/1_2/patterns.nim.o c_code/1_2/dfa.nim.o c_code/1_2/injectdestructors.nim.o c_code/1_2/liftlocals.nim.o c_code/1_2/lambdalifting.nim.o c_code/1_2/closureiters.nim.o c_code/1_2/transf.nim.o c_code/1_2/vmgen.nim.o c_code/2_2/vmdeps.nim.o c_code/1_2/vmmarshal.nim.o c_code/2_2/gorgeimpl.nim.o c_code/1_2/macrocacheimpl.nim.o c_code/1_2/evaltempl.nim.o c_code/2_2/vm.nim.o c_code/1_2/semmacrosanity.nim.o c_code/1_2/pluginsupport.nim.o c_code/1_2/plugins7locals.nim.o c_code/1_2/plugins7itersgen.nim.o c_code/1_2/plugins7active.nim.o c_code/1_2/semparallel.nim.o c_code/2_2/sem.nim.o c_code/1_2/ccgutils.nim.o c_code/1_2/ndi.nim.o c_code/1_2/cgendata.nim.o c_code/1_2/ccgmerge.nim.o c_code/1_2/enumtostr.nim.o c_code/2_2/stdlib_dynlib.nim.o c_code/1_2/cgen.nim.o c_code/1_2/passaux.nim.o c_code/1_2/depends.nim.o c_code/1_2/modules.nim.o c_code/1_2/jsgen.nim.o c_code/2_2/docgen2.nim.o c_code/1_2/main.nim.o c_code/2_2/scriptconfig.nim.o c_code/2_2/cmdlinehelper.nim.o c_code/2_2/nim.nim.o -ldl -lm -lrt
: SUCCESS
cd Nim ; bin/nim c koch
/bin/sh: 1: cd: can't cd to Nim
/bin/sh: 1: bin/nim: not found
Makefile:33: recipe for target 'Nim/koch' failed
make: *** [Nim/koch] Error 127
The command '/bin/sh -c apt-get update &&     apt-get install -y rsync time git apt-utils libpcre3-dev libtinfo-dev libz-dev libssl-dev libsqlite3-dev build-essential cmake ninja-build python-minimal wget &&     git submodule update --init &&     rm -rf /var/lib/apt/lists/* &&     ./make-dist-docker.sh &&     cd / &&     rm -rf /code/ &&     apt-get remove -y git apt-utils libpcre3-dev libssl-dev libsqlite3-dev build-essential cmake ninja-build python-minimal wget' returned a non-zero code: 2
make: *** [Makefile:112: docker] Error 2
```

looks like there are some path issues in there

**Comment by jacqueswww** [comment]
@arnetheduck could you check if the ` git submodule update --init ` worked? That error usually occurs when the git submodule didn't checkout.

**Comment by jacqueswww** [comment]
@arnetheduck alright please try now, had to replicate sub module to get it to work.

**Comment by refi64** [comment]
Not sure if by accident or not, but you completely deleted the Nim submodule. Also it wasn't working inside the container because the submodule doesn't exist anymore and you added Nim to your .dockerignore. Instead, you can re-add the submodule to the repo, and either:

- Leave Nim in the .dockerignore, re-add the submodule, then run `git submodule update--init` inside the script.
- Remove Nim from the .dockerignore, and replace it with the individual built files inside the Nim directory. (i.e. make sure only binaries you want to ignore inside the Nim directory are in the .dockerignore.)

**Comment by jacqueswww** [comment]
Yeah totally missed the deletion, will sort out tomorrow.

**Comment by jacqueswww** [comment]
Alright, just forced push the necessary changes. Holding thumbs this is all that's needed :^)

**Comment by arnetheduck** [comment]
@refi64 thanks for the comments.. I don't really do docker, so if there's anything else patches are very welcome - it "worked" for me now, to the extent that `docker build` completed.

**Pull request merged**
